version: '3'

services:
  frontend:
    image: mplabci.azurecr.io/warmup-frontend:v1
    ports:
      - "8080:3000"
    restart: always
    depends_on:
      - api

  api:
    image: mplabci.azurecr.io/warmup-backend:v1
    ports:
      - "8090:8080"
    volumes: &backend_volumes
      - warmupFiles:/app/files/
      
    restart: always
    depends_on:
      - worker

  worker:
    image: mplabci.azurecr.io/warmup-backend:v1
    ports:
      - "8203:8203"
    volumes: *backend_volumes
    restart: always
    command: ["python3" ,"-m", "scheduler.main"]