version: '3'

services:
  api:
    build: .
    ports:
      - "8070:8080"
    volumes:
      - ./files:/files
    restart: always
    depends_on:
      - worker
    env_file:
      - .env
  
  worker:
    build: .
    command: ["python3" ,"-m", "scheduler.main"]
    volumes:
      - ./files:/files
    restart: always
    ports:
      - "8203:8203"
    env_file:
      - .env
    
  
  