# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Frontend - Build and Deploy frontend image - ketchup983

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mplabci.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_39b6a1332c704a0a8e7e5045f070f548 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b83b6a8ec96b4be483c1b6b13569afba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mplabci.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_39b6a1332c704a0a8e7e5045f070f548 }}/mplabci/warmup-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ketchup983'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_413cd0faf62f4e3d81716faf5a0b733d }}
        images: 'mplabci.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_39b6a1332c704a0a8e7e5045f070f548 }}/mplabci/warmup-frontend:${{ github.sha }}'