# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ketchup983

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mplabci.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f267e9b230e147c4a4e295ba2962f0dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b20a34b745d466abedcd61d7402e9ba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mplabci.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f267e9b230e147c4a4e295ba2962f0dc }}/warmup-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ketchup983'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b76da4618e64fd4b614d49b4b348e04 }}
        images: 'mplabci.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f267e9b230e147c4a4e295ba2962f0dc }}/warmup-backend:${{ github.sha }}'